baseURL = 'https://grimmlabs.org/'
languageCode = 'en-us'
title = 'Grimm Labs'

# Taxonomies: This enables the "authors" feature
[taxonomies]
  team = "team"
  tag = "tags"
  category = "categories"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

# Menu Configuration
[[menu.main]]
  name = 'About'
  url = '/#about'
  weight = 1

[[menu.main]]
  name = 'Team'
  url = '/team/'
  weight = 2

[[menu.main]]
  name = 'Projects'
  url = '/#projects'
  weight = 3

[[menu.main]]
  name = 'Contact'
  url = '/#contact'
  weight = 4

[[menu.main]]
  name = 'Webring'
  url = 'https://webring.grimmlabs.org'
  weight = 5

[[menu.main]]
  name = 'Discord'
  url = 'https://discord.grimmlabs.org'
  weight = 6
